"""Install corrected CLI commands."""

from __future__ import annotations

import typer

from apex.cli_commands.analysis import register_analysis_commands
from apex.cli_commands.backtest_campaign_risk_mode import register_risk_mode_campaign_command
from apex.cli_commands.backtesting import register_backtesting_commands
from apex.cli_commands.daily_validation import register_daily_validation_commands
from apex.cli_commands.datasets import register_dataset_commands
from apex.cli_commands.evidence_bundle import register_evidence_bundle_commands
from apex.cli_commands.evidence_pipeline import register_evidence_pipeline_commands
from apex.cli_commands.forward_edge import register_forward_edge_commands
from apex.cli_commands.funded_history import register_funded_history_commands
from apex.cli_commands.h