#!/usr/bin/env python3
from __future__ import annotations

import ast
import json
from collections.abc import Iterable
from dataclasses import asdict, dataclass
from pathlib import Path


@dataclass(frozen=True, slots=True)
class SymbolHit:
    stage: str
    symbol: str
    path: str
    line: int
    kind: str


STAGES: dict[str, tuple[str, ...]] = {
    "candidate_generation": (
        "TradeCandidate",
        "generate_candidates",
        "generate_candidate",
        "build_candidate",
    ),
    "entry_and_geometry": (
        "EntryZone",
        "build_stop_geometry",
        "build_layered_targets",
        "_entry_zone",
        "_stop",
        "_targets",
    ),
    "evidence_and_methodology": (
        "mandatory_evidence",
        "methodology_gate",
        "strategy_verdict",
        "market_strategy_route",
        "METHODOLOGY_INCOMPATIBLE_STATE",
    ),
    "scoring_and_selection": (
        "derive_quality_dimensions",
        "rank_candidates",
        "select_candidate",
        "CandidateOutcome",
        "RankedCandidate",
    ),
    "actionability": (
        "classify_candidate_actionability",
        "EntryStatus",
        "is_entry_status_executable",
        "ActionabilityState",
    ),
    "setup_conversion": (
        "build_discovery_assessment",
        "_build_setup",
        "DiscoverySetup",
        "ConditionalExecutionPlan",
    ),
    "portfolio_assignment": (
        "build_opportunity_portfolio",
        "portfolio_from_setups",
        "OpportunityLane",
        "SequenceRole",
        "PortfolioDecisionState",
    ),
    "json_serialization": (
        "model_dump",
        "to_json",
        "json.dumps",
        "opportunity_portfolio",
        "focused_analysis",
    ),
    "cli_rendering": (
        "render_scan",
        "render_analysis",
        "console.print",
        "scan",
        "analyze",
    ),
}


def iter_files(root: Path) -> Iterable[Path]:
    for base in (root / "src", root / "tests"):
        if not base.exists():
            continue
        yield from sorted(base.rglob("*.py"))


def ast_symbols(path: Path) -> dict[str, tuple[int, str]]:
    try:
        tree = ast.parse(path.read_text(encoding="utf-8"))
    except (SyntaxError, UnicodeDecodeError):
        return {}
    found: dict[str, tuple[int, str]] = {}
    for node in ast.walk(tree):
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            found[node.name] = (node.lineno, "function")
        elif isinstance(node, ast.ClassDef):
            found[node.name] = (node.lineno, "class")
    return found


def find_hits(root: Path) -> list[SymbolHit]:
    files = list(iter_files(root))
    definitions = {path: ast_symbols(path) for path in files}
    hits: list[SymbolHit] = []

    for stage, symbols in STAGES.items():
        for symbol in symbols:
            exact = False
            for path, items in definitions.items():
                if symbol not in items:
                    continue
                line, kind = items[symbol]
                hits.append(
                    SymbolHit(
                        stage=stage,
                        symbol=symbol,
                        path=str(path.relative_to(root)),
                        line=line,
                        kind=kind,
                    )
                )
                exact = True
            if exact:
                continue
            for path in files:
                try:
                    lines = path.read_text(encoding="utf-8").splitlines()
                except UnicodeDecodeError:
                    continue
                for number, line in enumerate(lines, start=1):
                    if symbol in line:
                        hits.append(
                            SymbolHit(
                                stage=stage,
                                symbol=symbol,
                                path=str(path.relative_to(root)),
                                line=number,
                                kind="reference",
                            )
                        )
                        break

    return sorted(hits, key=lambda item: (item.stage, item.path, item.line, item.symbol))


def grouped_paths(hits: list[SymbolHit], prefix: str) -> dict[str, list[str]]:
    grouped: dict[str, set[str]] = {}
    for hit in hits:
        if hit.path.startswith(prefix):
            grouped.setdefault(hit.stage, set()).add(hit.path)
    return {stage: sorted(paths) for stage, paths in grouped.items()}


def write_markdown(root: Path, hits: list[SymbolHit], output: Path) -> None:
    sources = grouped_paths(hits, "src/")
    tests = grouped_paths(hits, "tests/")

    lines = [
        "# Apex Batch 0 — Trade Pipeline Source and Test Map",
        "",
        "Generated by static repository inspection. Runtime behavior is unchanged.",
        "",
        "## Pipeline map",
        "",
        "| Stage | Production source paths | Existing test paths | Coverage status |",
        "|---|---|---|---|",
    ]

    for stage in STAGES:
        source_paths = sources.get(stage, [])
        test_paths = tests.get(stage, [])
        if source_paths and test_paths:
            status = "source and focused tests located"
        elif source_paths:
            status = "source located; focused test not identified"
        elif test_paths:
            status = "test reference located; production definition not identified"
        else:
            status = "not identified by static probes"
        lines.append(
            "| "
            + " | ".join(
                (
                    stage,
                    "<br>".join(f"`{path}`" for path in source_paths) or "—",
                    "<br>".join(f"`{path}`" for path in test_paths) or "—",
                    status,
                )
            )
            + " |"
        )

    lines.extend(
        [
            "",
            "## Symbol-level findings",
            "",
            "| Stage | Symbol/probe | Kind | Path | Line |",
            "|---|---|---|---|---:|",
        ]
    )
    for hit in hits:
        lines.append(f"| {hit.stage} | `{hit.symbol}` | {hit.kind} | `{hit.path}` | {hit.line} |")

    lines.extend(
        [
            "",
            "## Validation boundary",
            "",
            "- Static discovery does not prove branch coverage.",
            "- Missing focused tests must be added before behavior-changing batches complete.",
            "- `apex scan` and `apex analyze` must retain shared canonical analysis authority.",
        ]
    )
    output.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> int:
    root = Path.cwd()
    if not (root / "pyproject.toml").exists():
        raise SystemExit("run from the Apex repository root")

    out_dir = root / "data" / "reports" / "geometry_audit"
    out_dir.mkdir(parents=True, exist_ok=True)

    hits = find_hits(root)
    json_path = out_dir / "pipeline_source_map.json"
    md_path = out_dir / "pipeline_source_map.md"

    json_path.write_text(
        json.dumps([asdict(hit) for hit in hits], indent=2) + "\n",
        encoding="utf-8",
    )
    write_markdown(root, hits, md_path)

    print(f"wrote {md_path.relative_to(root)}")
    print(f"wrote {json_path.relative_to(root)}")
    print(f"symbol hits: {len(hits)}")
    print(f"production files: {len({h.path for h in hits if h.path.startswith('src/')})}")
    print(f"test files: {len({h.path for h in hits if h.path.startswith('tests/')})}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
